### ISSUE TITLE
Could you also implement Indexed_init_with?

### ISSUE THREAD

**Issue by ghost** [QuietMisdreavus/init-with-rs#2]

**Comment by QuietMisdreavus** [comment]
So instead of the init closure taking no arguments, it takes its index? That's provided by the [`array-init`] crate, if you want to use that one instead. That author took a different approach to its implementation, so it already uses that interface.

[`array-init`]: https://crates.io/crates/array-init

**Comment by ghost** [comment]
I just made external counter.
